dist: trusty
sudo: required
addons:
  chrome: stable
matrix:
  fast_finish: true

language:
  node_js

node_js:
  - '9'
  - '8'
  - '6'

before_script:
  - export DISPLAY=:99.0;                  #
  - sh -e /etc/init.d/xvfb start; sleep 3; # for clipboard support
  - sudo apt install xsel                  #
  - node --version
  - npm --version

script:
  npm run ci

after_success:
  npm run cover
