language:
  node_js

node_js:
  - '9'
  - '8'
  - '6'

sudo: required
addons:
  chrome: stable
matrix:
  fast_finish: true

before_script:
  - node --version
  - npm --version

script:
  npm run ci

after_success:
  npm run cover
